runtime: python311

env_variables:
  GOOGLE_CLIENT_ID: "466918583342-44dugo1ikr921dr2ogkt9i6mcvh2ae0m.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  MARKETING_HUB_FOLDER_ID: "1FM66Jay8G6gpXsP-pLGwW64-FmqJszLa"
  NAMING_CONVENTION_DOC_ID: "1IqpsMdfAjGx3H2l6SyRWcRH3red40c6AosMORn0oQes"
  GEMINI_API_KEY: "YOUR_GEMINI_API_KEY_HERE"
  FLASK_ENV: "production"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

